export const GET_PRODUCTS_SUCCESS_ACTION = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE_ACTION = 'GET_PRODUCTS_FAILURE'

export const GET_PRODUCT_SUCCESS_ACTION = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE_ACTION = 'GET_PRODUCT_FAILURE'